In [1]:
import tensorflow as tf
import numpy as np

## Dataset

`tf.data.Dataset.from_tensors`
* Return a complete shape of the input array
    
`tf.data.Dataset.from_tensor_slides`
* Return the array after removing the first dimension of the input array

In [2]:
ARRAY_1 = np.array([[11,21,31,41,51], [12,14,16,18,20]])
ARRAY_2 = np.array([[0,9,8,7,6],[1,2,3,4,5]])

# tf.data.Dataset.from_tensors
DATASET_1 = tf.data.Dataset.from_tensors(ARRAY_1)
print('Dataset 1')
print(DATASET_1)
print('')

# tf.data.Dataset.from_tensor_slices
DATASET_2 = tf.data.Dataset.from_tensor_slices(ARRAY_2)
print('Dataset 2')
print(DATASET_2)
print('')

# tf.data.Dataset.from_tensors
DATASET_3 = tf.data.Dataset.from_tensors(np.array(np.random.rand(2,4,3)))
print('Dataset 3')
print(DATASET_3)
print('')

# tf.data.Dataset.from_tensor_slices
DATASET_4 = tf.data.Dataset.from_tensor_slices(np.array(np.random.rand(2,4,3)))
print('Dataset 4')
print(DATASET_4)
print('')

Dataset 1
<DatasetV1Adapter shapes: (2, 5), types: tf.int64>

Dataset 2
<DatasetV1Adapter shapes: (5,), types: tf.int64>

Dataset 3
<DatasetV1Adapter shapes: (2, 4, 3), types: tf.float64>

Dataset 4
<DatasetV1Adapter shapes: (4, 3), types: tf.float64>



## Iterator

`make_one_shot_iterator().get_next()`
* Only supports iterating once through a dataset, with no need for explicit initialization

`make_initializable_iterator()`
* An initializable iterator requires you to run an explicit iterator.initializer operation before using it.

In [5]:
# make_one_shot_iterator()

ITERATOR_1 = DATASET_1.make_one_shot_iterator().get_next()
ITERATOR_2 = DATASET_2.make_one_shot_iterator().get_next()

# Session
SESS = tf.Session()

print('DATASET 1')
print(SESS.run(ITERATOR_1))

print('')

for i in range(len(ARRAY_2)):
    print('DATASET 2')
    print(SESS.run(ITERATOR_2))

DATASET 1
[[11 21 31 41 51]
 [12 14 16 18 20]]

DATASET 2
[0 9 8 7 6]
DATASET 2
[1 2 3 4 5]


In [21]:
# make_initializable_iterator()
X, Y = tf.placeholder(tf.float32, shape = [None, 2]), tf.placeholder(tf.float32, shape = [None, 1])
DATASET = tf.data.Dataset.from_tensor_slices((X, Y))
TRAIN_DATA = (np.random.rand(10,2), np.random.rand(10,1))
TEST_DATA = (np.array([[1,2]]), np.array([[0]]))

ITERATOR = DATASET.make_initializable_iterator()
FEATURE, LABEL = ITERATOR.get_next()

print('TRAIN DATA')
SESS.run(ITERATOR.initializer, feed_dict = {X : TRAIN_DATA[0], Y : TRAIN_DATA[1]})
print(SESS.run([FEATURE, LABEL]))
    
print('')

print('TEST DATA')
SESS.run(ITERATOR.initializer, feed_dict = {X : TEST_DATA[0], Y : TEST_DATA[1]})
print(SESS.run([FEATURE, LABEL]))

TRAIN DATA
[array([0.4136121, 0.9556283], dtype=float32), array([0.38089103], dtype=float32)]

TEST DATA
[array([1., 2.], dtype=float32), array([0.], dtype=float32)]


## Data Transformation

In [10]:
ARRAY_3 = np.array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90])

DATASET = tf.data.Dataset.from_tensor_slices(ARRAY_3).repeat().shuffle(2).batch(3)
ITERATOR = DATASET.make_one_shot_iterator().get_next()

for i in range(len(ARRAY_3)):
    print(SESS.run(ITERATOR))

[99 97 98]
[95 94 96]
[92 93 91]
[99 98 90]
[97 95 96]
[94 93 91]
[92 90 98]
[97 99 96]
[94 93 95]
[91 92 99]
